### ISSUE TITLE
Data inici en el llistat de tasques d'usuari no correcte

### ISSUE THREAD

**Issue by ecarreras** [gisce/project-dashboard#34]
![image](https://user-images.githubusercontent.com/294235/27858678-6ae6025a-6176-11e7-8e16-48cbe6d5ce36.png)

**Comment by asimon91** [comment]
Thank you @ecarreras . As we commented, a possible solution to this is a function field (in OpenERP) that retrieves the create date of the first workone of each task, right?

In case that there's not any workdone, should this field be null?

**Comment by asimon91** [comment]
@ecarreras solved in #46 . Thanks!
